package hotel.pojo;
// Generated 02-dic-2016 0:37:51 by Hibernate Tools 4.3.1



/**
 * Edad generated by hbm2java
 */
public class Edad  implements java.io.Serializable {


     private char idEdad;
     private String edad;

    public Edad() {
    }

    public Edad(char idEdad, String edad) {
       this.idEdad = idEdad;
       this.edad = edad;
    }
   
    public char getIdEdad() {
        return this.idEdad;
    }
    
    public void setIdEdad(char idEdad) {
        this.idEdad = idEdad;
    }
    public String getEdad() {
        return this.edad;
    }
    
    public void setEdad(String edad) {
        this.edad = edad;
    }




}


