package hotel.pojo;
// Generated 02-dic-2016 0:37:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Habitacion generated by hbm2java
 */
public class Habitacion  implements java.io.Serializable {


     private Integer idHabitacion;
     private Planta planta;
     private Tipo tipo;
     private String numero;
     private Set ocupacions = new HashSet(0);
     private Set reservas = new HashSet(0);

    public Habitacion() {
    }

	
    public Habitacion(Planta planta, Tipo tipo, String numero) {
        this.planta = planta;
        this.tipo = tipo;
        this.numero = numero;
    }
    public Habitacion(Planta planta, Tipo tipo, String numero, Set ocupacions, Set reservas) {
       this.planta = planta;
       this.tipo = tipo;
       this.numero = numero;
       this.ocupacions = ocupacions;
       this.reservas = reservas;
    }
   
    public Integer getIdHabitacion() {
        return this.idHabitacion;
    }
    
    public void setIdHabitacion(Integer idHabitacion) {
        this.idHabitacion = idHabitacion;
    }
    public Planta getPlanta() {
        return this.planta;
    }
    
    public void setPlanta(Planta planta) {
        this.planta = planta;
    }
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public Set getOcupacions() {
        return this.ocupacions;
    }
    
    public void setOcupacions(Set ocupacions) {
        this.ocupacions = ocupacions;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


