package hotel.pojo;
// Generated 02-dic-2016 0:37:51 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * OcupacionId generated by hbm2java
 */
public class OcupacionId  implements java.io.Serializable {


     private int idHabitacion;
     private Date fecha;

    public OcupacionId() {
    }

    public OcupacionId(int idHabitacion, Date fecha) {
       this.idHabitacion = idHabitacion;
       this.fecha = fecha;
    }
   
    public int getIdHabitacion() {
        return this.idHabitacion;
    }
    
    public void setIdHabitacion(int idHabitacion) {
        this.idHabitacion = idHabitacion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OcupacionId) ) return false;
		 OcupacionId castOther = ( OcupacionId ) other; 
         
		 return (this.getIdHabitacion()==castOther.getIdHabitacion())
 && ( (this.getFecha()==castOther.getFecha()) || ( this.getFecha()!=null && castOther.getFecha()!=null && this.getFecha().equals(castOther.getFecha()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdHabitacion();
         result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
         return result;
   }   


}


