package hotel.pojo;
// Generated 02-dic-2016 0:37:51 by Hibernate Tools 4.3.1



/**
 * Ocupacion generated by hbm2java
 */
public class Ocupacion  implements java.io.Serializable {


     private OcupacionId id;
     private Habitacion habitacion;

    public Ocupacion() {
    }

    public Ocupacion(OcupacionId id, Habitacion habitacion) {
       this.id = id;
       this.habitacion = habitacion;
    }
   
    public OcupacionId getId() {
        return this.id;
    }
    
    public void setId(OcupacionId id) {
        this.id = id;
    }
    public Habitacion getHabitacion() {
        return this.habitacion;
    }
    
    public void setHabitacion(Habitacion habitacion) {
        this.habitacion = habitacion;
    }




}


