package hotel.pojo;
// Generated 02-dic-2016 0:37:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pax generated by hbm2java
 */
public class Pax  implements java.io.Serializable {


     private String idPax;
     private String pax;
     private Set reservas = new HashSet(0);

    public Pax() {
    }

	
    public Pax(String idPax, String pax) {
        this.idPax = idPax;
        this.pax = pax;
    }
    public Pax(String idPax, String pax, Set reservas) {
       this.idPax = idPax;
       this.pax = pax;
       this.reservas = reservas;
    }
   
    public String getIdPax() {
        return this.idPax;
    }
    
    public void setIdPax(String idPax) {
        this.idPax = idPax;
    }
    public String getPax() {
        return this.pax;
    }
    
    public void setPax(String pax) {
        this.pax = pax;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


