package hotel.pojo;
// Generated 02-dic-2016 0:37:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Planta generated by hbm2java
 */
public class Planta  implements java.io.Serializable {


     private Integer idPlanta;
     private String planta;
     private Set habitacions = new HashSet(0);

    public Planta() {
    }

	
    public Planta(String planta) {
        this.planta = planta;
    }
    public Planta(String planta, Set habitacions) {
       this.planta = planta;
       this.habitacions = habitacions;
    }
   
    public Integer getIdPlanta() {
        return this.idPlanta;
    }
    
    public void setIdPlanta(Integer idPlanta) {
        this.idPlanta = idPlanta;
    }
    public String getPlanta() {
        return this.planta;
    }
    
    public void setPlanta(String planta) {
        this.planta = planta;
    }
    public Set getHabitacions() {
        return this.habitacions;
    }
    
    public void setHabitacions(Set habitacions) {
        this.habitacions = habitacions;
    }




}


