package hotel.pojo;
// Generated 02-dic-2016 0:37:51 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private Integer idReserva;
     private Cliente cliente;
     private Habitacion habitacion;
     private Pax pax;
     private Regimen regimen;
     private Tipo tipo;
     private Date fechaEntrada;
     private Date fechaSalida;
     private boolean confirmada;
     private String edadN1;
     private String edadN2;
     private String edadN3;
     private Double totalconIva;

    public Reserva() {
    }

	
    public Reserva(Cliente cliente, Habitacion habitacion, Regimen regimen, Date fechaEntrada, Date fechaSalida, boolean confirmada) {
        this.cliente = cliente;
        this.habitacion = habitacion;
        this.regimen = regimen;
        this.fechaEntrada = fechaEntrada;
        this.fechaSalida = fechaSalida;
        this.confirmada = confirmada;
    }
    public Reserva(Cliente cliente, Habitacion habitacion, Pax pax, Regimen regimen, Tipo tipo, Date fechaEntrada, Date fechaSalida, boolean confirmada, String edadN1, String edadN2, String edadN3, Double totalconIva) {
       this.cliente = cliente;
       this.habitacion = habitacion;
       this.pax = pax;
       this.regimen = regimen;
       this.tipo = tipo;
       this.fechaEntrada = fechaEntrada;
       this.fechaSalida = fechaSalida;
       this.confirmada = confirmada;
       this.edadN1 = edadN1;
       this.edadN2 = edadN2;
       this.edadN3 = edadN3;
       this.totalconIva = totalconIva;
    }
   
    public Integer getIdReserva() {
        return this.idReserva;
    }
    
    public void setIdReserva(Integer idReserva) {
        this.idReserva = idReserva;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Habitacion getHabitacion() {
        return this.habitacion;
    }
    
    public void setHabitacion(Habitacion habitacion) {
        this.habitacion = habitacion;
    }
    public Pax getPax() {
        return this.pax;
    }
    
    public void setPax(Pax pax) {
        this.pax = pax;
    }
    public Regimen getRegimen() {
        return this.regimen;
    }
    
    public void setRegimen(Regimen regimen) {
        this.regimen = regimen;
    }
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }
    public Date getFechaEntrada() {
        return this.fechaEntrada;
    }
    
    public void setFechaEntrada(Date fechaEntrada) {
        this.fechaEntrada = fechaEntrada;
    }
    public Date getFechaSalida() {
        return this.fechaSalida;
    }
    
    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }
    public boolean isConfirmada() {
        return this.confirmada;
    }
    
    public void setConfirmada(boolean confirmada) {
        this.confirmada = confirmada;
    }
    public String getEdadN1() {
        return this.edadN1;
    }
    
    public void setEdadN1(String edadN1) {
        this.edadN1 = edadN1;
    }
    public String getEdadN2() {
        return this.edadN2;
    }
    
    public void setEdadN2(String edadN2) {
        this.edadN2 = edadN2;
    }
    public String getEdadN3() {
        return this.edadN3;
    }
    
    public void setEdadN3(String edadN3) {
        this.edadN3 = edadN3;
    }
    public Double getTotalconIva() {
        return this.totalconIva;
    }
    
    public void setTotalconIva(Double totalconIva) {
        this.totalconIva = totalconIva;
    }




}


