package hotel.pojo;
// Generated 02-dic-2016 0:37:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipo generated by hbm2java
 */
public class Tipo  implements java.io.Serializable {


     private Integer idTipo;
     private String tipo;
     private String imagen;
     private String descripcion;
     private Set precios = new HashSet(0);
     private Set habitacions = new HashSet(0);
     private Set reservas = new HashSet(0);

    public Tipo() {
    }

	
    public Tipo(String tipo) {
        this.tipo = tipo;
    }
    public Tipo(String tipo, String imagen, String descripcion, Set precios, Set habitacions, Set reservas) {
       this.tipo = tipo;
       this.imagen = imagen;
       this.descripcion = descripcion;
       this.precios = precios;
       this.habitacions = habitacions;
       this.reservas = reservas;
    }
   
    public Integer getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(Integer idTipo) {
        this.idTipo = idTipo;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getPrecios() {
        return this.precios;
    }
    
    public void setPrecios(Set precios) {
        this.precios = precios;
    }
    public Set getHabitacions() {
        return this.habitacions;
    }
    
    public void setHabitacions(Set habitacions) {
        this.habitacions = habitacions;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


